{
  "hash": "fc96b5b9ee5b3b086285baf7e3f3113b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Road Design Fragmentation: Northern Kentucky vs. Cincinnati\"\nsubtitle: \"Does municipal fragmentation produce worse pedestrian environments?\"\ndate: today\n---\n\n\n\n## Motivation\n\nCincinnati and Northern Kentucky share a metro economy separated by the Ohio River — and by a sharp political boundary. Cincinnati operates under a single city engineering department with a [Complete Streets ordinance](https://www.citybeat.com/news/cincinnati-adopts-complete-streets-policy-to-prioritize-pedestrian-safety-accessibility-14323235/) adopted in 2024. Northern Kentucky's urban core is governed by dozens of independent municipalities — Covington, Newport, Florence, Erlanger, Fort Mitchell, Fort Wright, and others — each setting its own road design standards, signal timing, and right-of-way rules.\n\nThe transit fragmentation literature documents how governance patchworks depress ridership. The hypothesis here is the same mechanism on road design: fragmented jurisdiction → inconsistent standards → pedestrian-hostile outcomes.\n\n---\n\n## Data Sources\n\nThree road inventory sources are combined, with official DOT data taking priority over OSM:\n\n| Source | Region | Coverage | Key fields |\n|--------|--------|----------|------------|\n| **ODOT Road Inventory** (TIMS) | Cincinnati / Hamilton Co. | 23,342 segments | Speed, lanes, lane width, bike lane, ADT, shoulder |\n| **KYTC Speed Limits** (ArcGIS REST) | NKy — state + city streets | 400 segments | Posted speed |\n| **KYTC LRS Shapefile** | NKy — state roads only | 747 segments | Lanes, lane width |\n| **OpenStreetMap** | Both | 49k segments | Highway type, speed, lanes, sidewalk, surface |\n\nOSM fills gaps where DOT data is absent; highway-type defaults fill any remaining nulls. All sources are spatially joined within 50 m of each OSM centroid.\n\n---\n\n## Pedestrian Hostility Index\n\nEach segment is scored 0–1 on each available dimension, then combined as a weighted mean over non-null components. Higher = more hostile to pedestrians.\n\n| Component | Weight | Priority |\n|-----------|--------|----------|\n| Posted speed | 30% | ODOT > KYTC > OSM > imputed |\n| Highway type | 25% | OSM (near-complete) |\n| Lane count | 20% | ODOT > KYTC > OSM > imputed |\n| Lane width | 10% | ODOT / KYTC only |\n| Sidewalk presence | 8% | OSM (~8% observed) |\n| Bike infrastructure | 4% | ODOT / OSM |\n| Surface quality | 3% | OSM (~18% observed) |\n\n### Data Coverage After DOT Join\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoverage <- read_csv(\"data/coverage_summary.csv\", show_col_types = FALSE)\n\ncoverage |>\n  mutate(across(where(is.numeric) & !n, \\(x) paste0(round(x, 1), \"%\"))) |>\n  rename(\n    Region             = region,\n    Segments           = n,\n    `Speed (DOT)`      = pct_speed_dot,\n    `Speed (OSM)`      = pct_speed_osm,\n    `Speed (imputed)`  = pct_speed_imputed,\n    `Lanes (DOT)`      = pct_lanes_dot,\n    `Lanes (OSM)`      = pct_lanes_osm,\n    `Lanes (imputed)`  = pct_lanes_imputed,\n    `Width observed`   = pct_width,\n    `Sidewalk observed`= pct_sidewalk,\n    `Bike observed`    = pct_bike\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Region                    | Segments|Speed (DOT) |Speed (OSM) |Speed (imputed) |Lanes (DOT) |Lanes (OSM) |Lanes (imputed) |Width observed |Sidewalk observed |Bike observed |\n|:-------------------------|--------:|:-----------|:-----------|:---------------|:-----------|:-----------|:---------------|:--------------|:-----------------|:-------------|\n|Cincinnati (Hamilton Co.) |    26677|89%         |3%          |8%              |92.7%       |3.1%        |4.2%            |43.6%          |6.3%              |7.3%          |\n|Northern Kentucky         |    12249|3.6%        |24.2%       |72.2%           |3.9%        |38.8%       |57.2%           |3.9%           |6.9%              |4.2%          |\n\n</div>\n:::\n:::\n\n\nThe asymmetry is stark: ODOT matches 89% of Cincinnati segments with official speed data; KYTC's state-road shapefile only reaches 3.7% of NKy. NKy's city and county roads — which carry most of the pedestrian activity — have no centralized official inventory available, only OSM. This is itself a governance finding: Cincinnati has an institutionally mapped road network; NKy doesn't.\n\n---\n\n## Results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroads        <- st_read(\"data/roads_hostility.gpkg\", quiet = TRUE)\nsummary_tbl  <- read_csv(\"data/hostility_summary.csv\", show_col_types = FALSE)\ntype_summary <- read_csv(\"data/type_summary.csv\",      show_col_types = FALSE)\n```\n:::\n\n\n### Overall Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  st_drop_geometry(roads) |> filter(region != \"Outside Study Area\"),\n  aes(x = hostility_index, fill = region, color = region)\n) +\n  geom_density(alpha = 0.35, linewidth = 0.8) +\n  scale_fill_manual(values  = c(\"Cincinnati (Hamilton Co.)\" = \"#2c3e50\",\n                                \"Northern Kentucky\"          = \"#c0392b\")) +\n  scale_color_manual(values = c(\"Cincinnati (Hamilton Co.)\" = \"#2c3e50\",\n                                \"Northern Kentucky\"          = \"#c0392b\")) +\n  scale_x_continuous(limits = c(0, 1)) +\n  labs(\n    title = \"Pedestrian Hostility Index Distribution\",\n    x     = \"Hostility Index (0 = friendly → 1 = hostile)\",\n    y     = \"Density\",\n    fill  = NULL, color = NULL\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/dist-plot-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary_tbl |>\n  mutate(\n    mean_hostility   = round(mean_hostility, 3),\n    median_hostility = round(median_hostility, 3),\n    pct_high         = paste0(round(pct_high, 1), \"%\"),\n    mean_speed       = round(mean_speed, 1),\n    mean_lanes       = round(mean_lanes, 2),\n    mean_width_ft    = round(mean_width_ft, 1),\n    length_km        = round(length_km, 0)\n  ) |>\n  rename(\n    Region              = region,\n    Segments            = n,\n    `Mean hostility`    = mean_hostility,\n    `Median hostility`  = median_hostility,\n    `% score > 0.6`     = pct_high,\n    `Mean speed (mph)`  = mean_speed,\n    `Mean lanes`        = mean_lanes,\n    `Mean lane width (ft)` = mean_width_ft,\n    `Network (km)`      = length_km\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Region                    | Segments| Mean hostility| Median hostility|% score > 0.6 | Mean speed (mph)| Mean lanes| Mean lane width (ft)| Network (km)|\n|:-------------------------|--------:|--------------:|----------------:|:-------------|----------------:|----------:|--------------------:|------------:|\n|Cincinnati (Hamilton Co.) |    26677|          0.341|            0.270|10.8%         |             27.8|       2.60|                 12.0|         6275|\n|Northern Kentucky         |    12249|          0.310|            0.176|12.4%         |             30.0|       1.83|                 12.4|         3014|\n\n</div>\n:::\n:::\n\n\n### By Road Type\n\nThe aggregate scores are similar, but the breakdown by highway type surfaces the real signal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntype_order <- c(\"primary\",\"secondary\",\"tertiary\",\"unclassified\",\"residential\")\n\ntype_summary |>\n  mutate(highway = factor(highway, levels = type_order)) |>\n  ggplot(aes(x = highway, y = mean_hostility, fill = region)) +\n  geom_col(position = \"dodge\", width = 0.65) +\n  scale_fill_manual(values = c(\"Cincinnati (Hamilton Co.)\" = \"#2c3e50\",\n                               \"Northern Kentucky\"          = \"#c0392b\")) +\n  scale_y_continuous(limits = c(0, 0.75)) +\n  labs(\n    title = \"Mean Hostility by Road Type\",\n    x = NULL, y = \"Mean hostility index\", fill = NULL\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(legend.position = \"bottom\", panel.grid.major.x = element_blank())\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/by-type-plot-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntype_summary |>\n  mutate(\n    highway        = factor(highway, levels = type_order),\n    mean_hostility = round(mean_hostility, 3),\n    mean_speed     = round(mean_speed, 1),\n    mean_lanes     = round(mean_lanes, 2)\n  ) |>\n  arrange(highway, region) |>\n  rename(\n    Region          = region,\n    `Road type`     = highway,\n    Segments        = n,\n    `Mean hostility`= mean_hostility,\n    `Mean speed`    = mean_speed,\n    `Mean lanes`    = mean_lanes\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Region                    |Road type    | Segments| Mean hostility| Mean speed| Mean lanes|\n|:-------------------------|:------------|--------:|--------------:|----------:|----------:|\n|Cincinnati (Hamilton Co.) |primary      |     2790|          0.534|       34.9|       3.78|\n|Northern Kentucky         |primary      |     1225|          0.592|       40.3|       3.67|\n|Cincinnati (Hamilton Co.) |secondary    |     3362|          0.472|       33.3|       3.41|\n|Northern Kentucky         |secondary    |     1405|          0.485|       35.6|       2.94|\n|Cincinnati (Hamilton Co.) |tertiary     |     3677|          0.374|       30.0|       2.61|\n|Northern Kentucky         |tertiary     |      730|          0.372|       30.0|       2.51|\n|Cincinnati (Hamilton Co.) |unclassified |      590|          0.253|       23.8|       2.21|\n|Northern Kentucky         |unclassified |      585|          0.240|       25.5|       1.84|\n|Cincinnati (Hamilton Co.) |residential  |    13028|          0.192|       19.6|       2.02|\n|Northern Kentucky         |residential  |     7268|          0.182|       24.8|       1.14|\n\n</div>\n:::\n:::\n\n\n**Primary roads are the clearest signal.** NKy primaries average 40.3 mph and score 0.592 hostility; Cincinnati primaries average 34.9 mph and score 0.534. This gap reflects design intent: NKy primary arterials (US routes through Florence, Erlanger, and Fort Mitchell / Fort Wright) function as high-speed through-routes while also serving local access, with no coordinating authority to enforce lower design speeds. Cincinnati's primary network operates under city engineering standards that impose more consistent constraints.\n\n### Speed Distribution on Primary Roads\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_drop_geometry(roads) |>\n  filter(region != \"Outside Study Area\", highway == \"primary\") |>\n  ggplot(aes(x = speed_final, fill = region, color = region)) +\n  geom_density(alpha = 0.35, linewidth = 0.8) +\n  scale_fill_manual(values  = c(\"Cincinnati (Hamilton Co.)\" = \"#2c3e50\",\n                                \"Northern Kentucky\"          = \"#c0392b\")) +\n  scale_color_manual(values = c(\"Cincinnati (Hamilton Co.)\" = \"#2c3e50\",\n                                \"Northern Kentucky\"          = \"#c0392b\")) +\n  scale_x_continuous(breaks = seq(15, 70, 5)) +\n  labs(\n    title = \"Posted Speed Distribution — Primary Roads Only\",\n    x = \"Posted speed (mph)\", y = \"Density\",\n    fill = NULL, color = NULL\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/speed-primary-1.png){width=768}\n:::\n:::\n\n\n---\n\n## Interpretation\n\nThe aggregate hostility scores are close (0.341 vs. 0.310), which would seem to undercut the fragmentation hypothesis — but the aggregate obscures where the effect lives. **On the road types that matter most for pedestrian mobility — primary and secondary arterials — NKy is meaningfully worse**, with higher design speeds and higher hostility scores.\n\nThe fragmentation mechanism here isn't \"NKy has uniformly worse roads.\" It's that the NKy patchwork can't enforce consistent design standards on its arterial network. Each municipality makes independent decisions about design speed, access management, and pedestrian accommodation on roads that carry cross-jurisdictional traffic. The result is a primary road network calibrated for throughput, not for the pedestrian trying to walk from Newport to Covington.\n\nThe data coverage asymmetry is also worth flagging: Cincinnati has a comprehensive official road inventory; NKy doesn't. That institutional gap is a precondition for the design gap — you can't coordinate what you haven't measured.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}